# -*- coding: utf-8 -*-
{
    'name': "Investment Portfolio",
    'author': "Elmeri Niemelä",
    'website': "https://eniemela.fi",
    'license': 'LGPL-3',
    'category': 'Investment Portfolio',
    'version': '2.1.7',
    'depends': [
        'mail',
        'timeago_widget',
        'api_endpoint',
    ],
    'installable': True,
    'application': True,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/users.xml',
        'data/decimal.xml',
        'data/ir_cron_data.xml',
        'data/endpoints.xml',
        'data/export.xml',
        'views/investment_timeseries.xml',
        'views/investment_portfolio.xml',
        'views/investment_category.xml',
        'views/investment_milestone.xml',
        'views/investment_asset_price.xml',
        'views/investment_asset_realized.xml',
        'views/investment_position_transaction.xml',
        'views/investment_asset.xml',
        'views/investment_position.xml',
        'views/res_company.xml',
        'views/menuitems.xml',
    ],
    'demo': [
        'demo/categories.xml',
        'demo/portfolios.xml',
        'demo/assets.xml',
        'demo/investment.asset.price.csv',
        'demo/investment.position.transaction.csv',
    ],
}
