# -*- coding: utf-8 -*-
{
    'name': "Investment Portfolio",
    'author': "Elmeri Niemelä",
    'website': "https://eniemela.fi",
    'license': 'LGPL-3',
    'category': 'Uncategorized',
    'version': '1.2',
    'depends': [
        'mail',
        'timeago_widget',
        'api_endpoint',
    ],
    'installable': True,
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'data/users.xml',
        'data/decimal.xml',
        'data/ir_cron_data.xml',
        'data/endpoints.xml',
        'data/export.xml',
        'views/investment_timeseries.xml',
        'views/investment_category.xml',
        'views/investment_milestone.xml',
        'views/investment_asset_price.xml',
        'views/investment_asset_realized.xml',
        'views/investment_asset_transaction.xml',
        'views/investment_asset.xml',
        'views/menuitems.xml',
    ],
}
