# -*- coding: utf-8 -*-
{
    'name': "Investment Portfolio",
    'author': "Elmeri Niemelä",
    'website': "https://eniemela.fi",
    'license': 'LGPL-3',
    'category': 'Investment Portfolio',
    'version': '2.8.24',
    'depends': [
        'mail',
        'timeago_widget',
        'chart_widget',
        'api_endpoint',
        'version_control',
    ],
    'installable': True,
    'application': True,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/users.xml',
        'data/decimal.xml',
        'data/ir_cron_data.xml',
        'data/endpoints.xml',
        'data/export.xml',
        'views/investment_timeseries.xml',
        'views/investment_portfolio.xml',
        'views/investment_category.xml',
        'views/investment_exchange_gap.xml',
        'views/investment_exchange.xml',
        'views/investment_milestone.xml',
        'views/investment_period.xml',
        'views/investment_period_position.xml',
        'views/investment_asset_price.xml',
        'views/investment_asset_realized.xml',
        'views/investment_asset_split.xml',
        'views/investment_position_move.xml',
        'views/investment_position_note.xml',
        'views/investment_position_tag.xml',
        'views/investment_position_transaction.xml',
        'views/investment_position.xml',
        'views/investment_asset.xml',
        'views/res_currency.xml',
        'views/res_company.xml',
        'report/investment_asset_realized_report.xml',
        'views/menuitems.xml',
    ],
    'demo': [
        'demo/categories.xml',
        'demo/portfolios.xml',
        'demo/ibkr_assets.xml',
        'demo/ibkr_positions.xml',
        'demo/assets.xml',
        'demo/investment.asset.price.csv',
        'demo/investment.position.transaction.csv',
    ],
    'assets': {
        'web.assets_backend': [
            'investment_portfolio/static/src/dashboard/*',
        ],
    }
}
