# -*- coding: utf-8 -*-

import logging
import secrets
import base64
import json
import xmlrpc.client
import ast
from lxml import etree
from odoo import models, tools, fields, api, _
from odoo.tools.safe_eval import safe_eval, test_python_expr, wrap_module, datetime, dateutil

requests = wrap_module(__import__('requests'), ['get', 'post', 'put', 'delete'])
io = wrap_module(__import__('io'), ['StringIO', 'BytesIO'])
pandas = wrap_module(__import__('pandas'), ['read_csv', 'read_excel'])
re = wrap_module(__import__('re'), ['findall',])
json = wrap_module(__import__('json'), ['loads','dumps'])
xmltodict = wrap_module(__import__('xmltodict'), ['parse'])
dicttoxml = wrap_module(__import__('dicttoxml'), ['dicttoxml'])

import lxml
lxml_mods = ['etree']
for mod in lxml_mods:
    __import__('lxml.%s' % mod)
lxml = wrap_module(__import__('lxml'), {mod: getattr(lxml, mod).__all__ for mod in lxml_mods})



_logger = logging.getLogger(__name__)


class ApiEndpoint(models.Model):
    _name = 'api.endpoint'
    _description = 'API Endpoint'
    _inherit = ['mail.thread']

    def _get_globals(self, params):
        return {
            'self': self.with_user(self.user_id),
            'params': params,
            'response': 'Message received.',
            'msgs': self.env['api.message'].browse(),
            'json': json,
            'xmltodict': xmltodict,
            'dicttoxml': dicttoxml,
            'pandas': pandas,
            'requests': requests,
            'io': io,
            're': re,
            'etree': lxml.etree,
            'getattr': getattr,
        }


    name = fields.Char(
        required=True,
        tracking=True,
    )

    direction = fields.Selection(
        selection=[
            ('outbound', 'Outbound'),
            ('inbound', 'Inbound'),
        ],
        required=True,
        tracking=True,
        default='outbound',
    )

    role = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('passive', 'Passive'),
        ],
        required=True,
        tracking=True,
        default='active',
    )

    user_id = fields.Many2one(
        comodel_name='res.users',
        string='User',
        default=lambda self: self.env.user,
        required=True,
        ondelete='restrict',
    )


    comm_method = fields.Selection(
        string="Communication",
        selection=[
            ('get', 'HTTP GET'),
            ('post', 'HTTP POST'),
            ('delete', 'HTTP DELETE'),
            ('put', 'HTTP PUT'),
            ('xmlrpc', 'XML-RPC'),
            ('jsonrpc', 'JSON-RPC'),
            ('sftp', 'SFTP'),
        ],
        required=True,
        tracking=True,
        default='get',
    )

    file_format = fields.Selection(
        selection=[
            ('json', 'JSON'),
            ('xml', 'XML'),
            ('csv', 'CSV'),
            ('zip', 'ZIP'),
            ('pdf', 'PDF'),
        ],
        required=True,
        tracking=True,
        default='json',
    )

    sequence_id = fields.Many2one(
        comodel_name='ir.sequence',
        required=True,
        tracking=True,
        ondelete='restrict',
    )

    authorization = fields.Char(
        tracking=True,
        default=lambda self: secrets.token_urlsafe(),
    )

    location = fields.Char(
        required=True,
        tracking=True,
        default='',
    )

    url = fields.Char(compute='_compute_url')

    ttl = fields.Integer(
        string="TTL",
        default=7,
        tracking=True,
    )

    auto_consume = fields.Boolean(
        default=True,
        tracking=True,
    )

    auto_commit = fields.Boolean(
        default=True,
        tracking=True,
    )

    auto_code = fields.Boolean(
        default=True,
        tracking=True,
    )

    hardcoded_producer = fields.Text(
        compute='_compute_hardcoded'
    )

    hardcoded_consumer = fields.Text(
        compute='_compute_hardcoded'
    )

    xslt = fields.Text(
        string="XSLT",
        tracking=True,
        help="XSLT transformation.",
    )

    documentation = fields.Html()

    test_example = fields.Text(
        string="Test Example",
        help="Example code to test the integration.",
    )

    producer = fields.Text(
        string="Producer (READ)",
        tracking=True,
        help="Produces a list of new message. The output will be passed to consumer.",
    )

    consumer = fields.Text(
        string="Consumer (CREATE, WRITE, DELETE)",
        tracking=True,
        help="consumees a list of messages generated by the producer. The result will be imported to Odoo or send to an external system.",
    )

    msg_ids = fields.One2many(
        comodel_name='api.message',
        inverse_name='endpoint_id',
        readonly=True
    )

    msg_count = fields.Integer(
        string="Messages",
        compute='_compute_msg_count',
    )


    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('sequence_id'):
                name = vals['name']
                code = ''.join(c[:1].lower() for c in name.split())

                vals['sequence_id'] = self.env['ir.sequence'].create({
                    'name': 'API: %s' % name,
                    'prefix': 'api_%s_' % code,
                    'company_id': False,
                }).id
        return super().create(vals_list)


    @api.depends('msg_ids')
    def _compute_msg_count(self):
        for rec in self:
            rec.msg_count = len(rec.msg_ids)

    @api.depends('comm_method', 'role', 'direction', 'file_format')
    def _compute_url(self):
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url').rstrip('/')
        for rec in self:
            url = False
            if rec.comm_method in ['post', 'put', 'delete'] and rec.direction == 'inbound' and rec.role == 'passive' and rec.location:
                url = f'{base_url}/api-endpoint/v1/{rec.location}'
            rec.url = url

    @api.depends('comm_method', 'role', 'direction', 'file_format')
    def _compute_hardcoded(self):
        for rec in self:
            hardcoded_producer = ''
            hardcoded_consumer = ''
            if rec.auto_code:
                if rec.comm_method in ['post', 'put', 'delete'] and rec.direction == 'inbound' and rec.role == 'passive':
                    if rec.file_format == 'json':
                        hardcoded_producer += "obj = json.loads(params['data'])\n"
                    elif rec.file_format == 'xml':
                        hardcoded_producer += "obj = etree.fromstring(params['data'])\n"
                        if (rec.xslt or '').strip():
                            hardcoded_consumer += 'obj = etree.XSLT(etree.XML(self.xslt))(obj)\n'
                elif rec.comm_method == 'xmlrpc' and rec.direction == 'outbound' and rec.role == 'active':
                    hardcoded_producer += 'obj = params'
                    hardcoded_consumer += (
                        "proxy = self.xmlrpc_proxy('https://%s@%s' % (self.authorization, self.location))\n"
                        "method = obj.pop('method', 'test')\n"
                        "args = obj.pop('args', tuple())\n"
                        "kwargs = obj.pop('kwargs', dict())\n"
                        "getattr(proxy, method)(*args, **kwargs)\n"
                    )


            rec.hardcoded_producer = hardcoded_producer
            rec.hardcoded_consumer = hardcoded_consumer


    def action_run(self):
        globals_dict = self.run({})
        return globals_dict.get('action', None)

    def action_test(self):
        globals_dict = self._get_globals(params={})
        safe_eval(self.test_example or '', globals_dict, mode="exec", nocopy=True)


    def run(self, params):
        self.ensure_one()
        globals_dict = self._get_globals(params=params)
        safe_eval((self.hardcoded_producer or '') + (self.producer or ''), globals_dict, mode="exec", nocopy=True)
        self.store(globals_dict)
        if self.auto_commit:
            self.env.cr.commit()
        if self.auto_consume:
            self.consume(globals_dict)
        return globals_dict

    def consume(self, globals_dict):
        safe_eval((self.hardcoded_consumer or '') + (self.consumer or ''), globals_dict, mode="exec", nocopy=True)
        globals_dict['msgs'].write({'state': 'consumed'})
        if self.auto_commit:
            self.env.cr.commit()


    def store(self, globals_dict):
        self.ensure_one()
        Msg = self.env['api.message'].with_context(default_endpoint_id=self.id)
        msgs = Msg.browse()
        if 'obj' in globals_dict:
            obj = globals_dict['obj']
            bytesdata = self.obj_to_bytes(obj)
            msgs += Msg.create({'content': base64.b64encode(bytesdata), 'params': str(globals_dict['params'])})
        elif 'objs' in globals_dict:
            for obj in globals_dict['objs']:
                bytesdata = self.obj_to_bytes(obj)
                msgs += Msg.create({'content': base64.b64encode(bytesdata), 'params': str(globals_dict['params'])})
        else:
            raise RuntimeError("No objs to store! The producer code should assign either 'obj' or 'objs'!")
        globals_dict['msgs'] = msgs



    def assert_obj_type(self, obj):
        if self.file_format == 'json':
            assert isinstance(obj, (list, dict)), str(type(obj))
        elif self.file_format == 'xml':
            assert isinstance(obj, (etree._Element)), str(type(obj))
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")


    def bytes_to_obj(self, bytesdata):
        self.ensure_one()
        if self.file_format == 'json':
            obj = json.loads(bytesdata)
        elif self.file_format == 'xml':
            obj = etree.fromstring(bytesdata)
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")
        self.assert_obj_type(obj)
        return obj


    def obj_to_bytes(self, obj):
        self.ensure_one()
        if self.file_format == 'json':
            bytesdata = json.dumps(obj, sort_keys=True, indent=4).encode()
        elif self.file_format == 'xml':
            bytesdata = etree.tostring(obj, pretty_print=True, xml_declaration=True, encoding='utf-8')
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")
        assert isinstance(bytesdata, bytes)
        return bytesdata



    @api.model
    def process_inbound_http(self, method, location, auth, params):
        assert method in ['get', 'post', 'delete', 'put']
        endpoint = self.sudo().search([
                ('comm_method', '=', method),
                ('location', '=', location),
                ('authorization', 'in', [auth, False]),
                ('role', '=', 'passive'),
                ('direction', '=', 'outbound' if method == 'get' else 'inbound'),
            ],
            limit=1,
        )
        if not endpoint:
            raise RuntimeError(f"Endpoint not found: {method=}, {location=} {auth=}")

        globals_dict = endpoint.run(params)
        return globals_dict['response']


    def next_from_queue(self):
        self.ensure_one()
        Msg = self.env['api.message']
        self.env.cr.execute(f"SELECT id FROM {Msg._table} WHERE endpoint_id=%s AND state='produced' ORDER BY name ASC, id ASC LIMIT 1 FOR UPDATE SKIP LOCKED", (self.id,))
        ids = self.env.cr.fetchall()
        if ids:
            return Msg.browse(ids[0])
        return Msg.browse()


    def odoo_xmlrpc_proxy(self, params):
        self.ensure_one()
        proxy = self.xmlrpc_proxy(self.location)
        authorization = safe_eval(self.authorization, self._get_globals(params=params))
        return proxy, *authorization

    def xmlrpc_proxy(self, url):
        return xmlrpc.client.ServerProxy(url)
