# -*- coding: utf-8 -*-

import logging
import secrets
import base64
import json
from lxml import etree
from odoo import models, tools, fields, api, _
from odoo.tools.safe_eval import safe_eval, test_python_expr, wrap_module, datetime, dateutil

_logger = logging.getLogger(__name__)


class ApiEndpoint(models.Model):
    _name = 'api.endpoint'
    _description = 'API Endpoint'
    _inherit = ['mail.thread']

    name = fields.Char(
        required=True,
        tracking=True,
    )

    directon = fields.Selection(
        selection=[
            ('outbound', 'Outbound'),
            ('inbound', 'Inbound'),
        ],
        required=True,
        tracking=True,
        default='outbound',
    )

    role = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('passive', 'Passive'),
        ],
        required=True,
        tracking=True,
        default='active',
    )

    user_id = fields.Many2one(
        comodel_name='res.users',
        string='User',
        default=lambda self: self.env.user,
        required=True,
        ondelete='restrict',
    )


    comm_method = fields.Selection(
        string="Communication",
        selection=[
            ('get', 'HTTP GET'),
            ('post', 'HTTP POST'),
            ('delete', 'HTTP DELETE'),
            ('put', 'HTTP PUT'),
            ('xmlrpc', 'XML-RPC'),
            ('jsonrpc', 'JSON-RPC'),
            ('sftp', 'SFTP'),
        ],
        required=True,
        tracking=True,
        default='get',
    )

    file_format = fields.Selection(
        selection=[
            ('json', 'JSON'),
            ('xml', 'XML'),
            ('csv', 'CSV'),
            ('zip', 'ZIP'),
            ('pdf', 'PDF'),
        ],
        required=True,
        tracking=True,
        default='json',
    )

    sequence_id = fields.Many2one(
        comodel_name='ir.sequence',
        required=True,
        tracking=True,
        ondelete='restrict',
    )

    authorization = fields.Char(
        required=True,
        tracking=True,
        default=lambda self: secrets.token_urlsafe(),
    )

    location = fields.Char(
        required=True,
        tracking=True,
        default='',
    )

    producer = fields.Text(
        tracking=True,
        help="Produces a list of new message. The output will be passed to processor.",
        default="objs = self.default_produce(params, bytesdata)",
    )

    processor = fields.Text(
        tracking=True,
        help="Processes a list of messages generated by the producer. The result will be imported to Odoo or send to an external system.",
        default="response = self.default_process(params, objs)"
    )

    msg_ids = fields.One2many(
        comodel_name='api.message',
        inverse_name='endpoint_id',
        readonly=True
    )

    msg_count = fields.Integer(
        compute='_compute_msg_count'
    )

    ttl = fields.Integer(default=7)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('sequence_id'):
                name = vals['name']
                code = ''.join(c[:1].lower() for c in name.split())

                vals['sequence_id'] = self.env['ir.sequence'].create({
                    'name': 'API: %s' % name,
                    'prefix': 'api_%s_' % code,
                    'company_id': False,
                }).id
        return super().create(vals_list)


    @api.depends('msg_ids')
    def _compute_msg_count(self):
        for record in self:
            record.msg_count = len(record.msg_ids)



    def fetch(self):
        pass


    def default_produce(self, params=None, bytesdata=None):
        objs = []
        if bytesdata:
            objs.append(self.bytes_to_obj(bytesdata))

        return objs

    def default_process(self, params, objs):
        return []


    def exec_produce_code(self, params=None, bytesdata=None):
        self.ensure_one()
        globals_dict = {'self': self.with_user(self.user_id), 'params': params, 'bytesdata': bytesdata}
        safe_eval(self.producer, globals_dict, mode="exec", nocopy=True)
        return globals_dict['objs']

    def exec_process_code(self, params=None, objs=None):
        self.ensure_one()
        globals_dict = {'self': self.with_user(self.user_id), 'params': params, 'objs': objs}
        safe_eval(self.processor, globals_dict, mode="exec", nocopy=True)
        return globals_dict['response']

    def store(self, params, objs):
        self.ensure_one()
        Msg = self.env['api.message'].with_context(default_endpoint_id=self.id)
        for obj in objs:
            bytesdata = self.obj_to_bytes(obj)
            Msg.create({'content': base64.b64encode(bytesdata), 'params': str(params)})

    def assert_obj_type(self, obj):
        if self.file_format == 'json':
            assert isinstance(obj, (list, dict)), str(type(obj))
        elif self.file_format == 'xml':
            assert isinstance(obj, (etree._Element)), str(type(obj))
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")


    def bytes_to_obj(self, bytesdata):
        self.ensure_one()
        if self.file_format == 'json':
            obj = json.loads(bytesdata)
        elif self.file_format == 'xml':
            obj = etree.fromstring(bytesdata)
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")
        self.assert_obj_type(obj)
        return obj


    def obj_to_bytes(self, obj):
        self.ensure_one()
        if self.file_format == 'json':
            bytesdata = json.dumps(obj, sort_keys=True, indent=4).encode()
        elif self.file_format == 'xml':
            bytesdata = etree.tostring(obj, pretty_print=True, xml_declaration=True, encoding='utf-8')
        else:
            raise NotImplementedError(f"Invalid file format: {self.file_format}")
        assert isinstance(bytesdata, bytes)
        return bytesdata



    @api.model
    def process_inbound_http(self, method, location, auth, params, data):
        assert method in ['get', 'post', 'delete', 'put']
        endpoint = self.sudo().search([
                ('comm_method', '=', method),
                ('location', '=', location),
                ('authorization', '=', auth),
                ('role', '=', 'passive')
            ],
            limit=1,
        )
        if not endpoint:
            raise RuntimeError(f"Endpoint not found: {method=}, {location=} {auth=}")

        objs = endpoint.exec_produce_code(params, data)
        endpoint.store(params, objs)
        response = endpoint.exec_process_code(params, objs)
        return response


    def next_from_queue(self):
        self.ensure_one()
        Msg = self.env['api.message']
        self.env.cr.execute(f"SELECT id FROM {Msg._table} WHERE endpoint_id=%s AND state='waiting' ORDER BY name ASC, id ASC LIMIT 1 FOR UPDATE SKIP LOCKED", (self.id,))
        ids = self.env.cr.fetchall()
        if ids:
            return Msg.browse(ids[0])
        return Msg.browse()