# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

class InformationMonitoringData(models.Model):
    _name = 'information.monitoring.data'
    _description = 'Information Monitoring Data'

    name = fields.Char(required=True)
    description = fields.Text()

    checksum = fields.Text(
        help=(
            "The checksums are generated by the following command for electronic files:\n"
            "md5deep -l -r . > ~/check.md5"
            "\n"
            "Verify with the following command:\n"
            "md5deep -l -r -x ~/check.md5 ."
            "\n"
            "See http://md5deep.sourceforge.net/"
        )
    )

    copy_ids = fields.One2many(
        comodel_name='information.monitoring.copy',
        inverse_name='data_id',
        string='Copies',
    )


class InformationMonitoringLocation(models.Model):
    _name = 'information.monitoring.location'
    _description = 'Information Monitoring Location'

    name = fields.Char(required=True)
    description = fields.Text()

    copy_ids = fields.One2many(
        comodel_name='information.monitoring.copy',
        inverse_name='location_id',
        string='Copies',
    )

class InformationMonitoringCopy(models.Model):
    _name = 'information.monitoring.copy'
    _description = 'Information Monitoring Copy'

    name = fields.Char(compute='_compute_name', store=True)
    location_id = fields.Many2one(
        comodel_name='information.monitoring.location',
        required=True,
        ondelete="restrict",
    )
    data_id = fields.Many2one(
        comodel_name="information.monitoring.data",
        required=True,
        ondelete="restrict",
    )
    description = fields.Text()

    medium = fields.Selection(
        selection=[
            ('external-hard-drive', 'External Hard Drive'),
            ('internal-hard-drive', 'Internal Hard Drive'),
            ('usb-stick', 'USB Stick'),
            ('paper', 'Paper'),
        ],
        required=True,
        default='external-hard-drive',
    )

    dtype = fields.Selection(
        selection=[
            ('directory', 'Directory'),
            ('file', 'Single File'),
        ],
        required=True,
        default='directory',
    )

    @api.depends('location_id.name', 'data_id.name', 'dtype', 'medium')
    def _compute_name(self):
        for record in self:
            record.name = "%s - %s (%s/%s)" % (record.location_id.name, record.data_id.name, record.dtype, record.medium)
