#!/usr/bin/env python3
"""Parse IBKR activity statement CSV files into ledger-style CSV files."""
import csv
import re
from collections import defaultdict
import dataclasses
from datetime import date, datetime, timezone
from decimal import Decimal, InvalidOperation
from typing import Optional
from zoneinfo import ZoneInfo
import hashlib

def parse_decimal(value: str) -> Optional[Decimal]:
    text = value.strip().replace(",", "")
    if not text or text == "--":
        return None
    try:
        return Decimal(text)
    except InvalidOperation:
        return None


def fmt_decimal(value: Decimal) -> str:
    text = format(value, "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    if text == "-0":
        return "0"
    return text


def normalize_time(value: str, source_timezone: Optional[ZoneInfo]) -> datetime:
    normalized = value.replace(",", "", 1).strip()
    if re.match(r"^\d{4}-\d{2}-\d{2}$", normalized):
        normalized = f"{normalized} 12:00:00"
    result = datetime.strptime(normalized, "%Y-%m-%d %H:%M:%S")
    result = result.replace(tzinfo=source_timezone).astimezone(ZoneInfo("Europe/Helsinki")) # TODO: Fix the ID scheme so that we can change this to UTC without creating new records
    return result


def is_total_label(value: str) -> bool:
    return value.strip().lower().startswith("total")

@dataclasses.dataclass(frozen=True)
class LedgerRow:
    id: str = dataclasses.field(init=False)
    ticker: str
    time: datetime
    quantity: Decimal
    price: Decimal
    payment_currency: Decimal
    type: str
    description: str
    cotx_id: Optional[str] = None

    _export_fields = (
        ('external_ref',        lambda row: row.id),
        ('ticker',              lambda row: row.ticker),
        ('time',                lambda row: row.time.astimezone(timezone.utc).replace(tzinfo=None).strftime("%Y-%m-%d %H:%M:%S")),
        ('quantity',            lambda row: fmt_decimal(row.quantity)),
        ('exchange_rate',       lambda row: fmt_decimal(row.price)),
        ('payment_currency',    lambda row: fmt_decimal(row.payment_currency)),
        # ('type',                lambda row: row.type),
        ('description',         lambda row: row.description),
        # ('cotx_id',             lambda row: row.cotx_id or ""),
    )

    def export(self):
        return {name: func(self) for name, func in self._export_fields}

    def __post_init__(self) -> None:
        # adjustments are generated by this script; ID depends only on type, ticker, and period start
        assert self.type, "Type is required"
        if self.type == 'adjustment':
            components: list[object] = [self.type, self.ticker, self.time.date().replace(day=1)]
        else:
            components: list[object] = [
                self.type, self.ticker, self.time, self.quantity,
                hashlib.sha256(self.description.encode()).hexdigest()[:6].upper() if self.type == "fee" else "",
            ]
        tokens: list[str] = []
        for component in components:
            if isinstance(component, Decimal):
                normalized = fmt_decimal(component).replace('-', 'm').replace('.', 'd')
            elif isinstance(component, datetime):
                normalized = component.strftime("%Y%m%dT%H%M%S")
            elif isinstance(component, date):
                normalized = component.strftime("%Y%m%d")
            elif isinstance(component, str):
                normalized = component
            elif not component:
                continue
            else:
                raise ValueError(f"Unknown type {component.__class__.__name__}: {repr(component)}")
            sanitized = re.sub(r"[^A-Za-z0-9.-]+", "_", normalized.strip()).strip("_")
            tokens.append(sanitized or "")
        self.force_set('id',  f"ibkr_tx_{'_'.join(t for t in tokens if t)}")

    def force_set(self, field, value):
        assert field in ('id', 'cotx_id'), "Only id and cotx_id can be mutated."
        object.__setattr__(self, field,  value)


class IBKRParser:
    def __init__(self, currency_rate, starting_balances) -> None:
        self.currency_rate = currency_rate
        self.starting_balances = starting_balances

    def extract_ledger_rows(self, buffer) -> list[dict]:
        rows: list[LedgerRow] = []
        commission_currency: Optional[str] = None
        cash_report_scope: Optional[str] = None
        fee_dates: list[datetime] = []
        sales_taxes: list[tuple[str, Decimal]] = []
        zero = Decimal("0")
        one = Decimal("1")
        source_timezone = ZoneInfo("America/New_York")
        statement_timezones = {
            "EST": "America/New_York", "EDT": "America/New_York",
            "CST": "America/Chicago", "CDT": "America/Chicago",
            "MST": "America/Denver", "MDT": "America/Denver",
            "PST": "America/Los_Angeles", "PDT": "America/Los_Angeles",
            "UTC": "UTC", "GMT": "UTC",
        }
        # (currency_col, time_col, description_col, amount_col, row_type)
        section_columns = {
            "Deposits & Withdrawals": (2, 3, 4, 5, "transfer"),
            "Fees": (3, 4, 5, 6, "fee"),
            "Dividends": (2, 3, 4, 5, "dividend"),
            "Withholding Tax": (2, 3, 4, 5, "tax"),
            "Interest": (2, 3, 4, 5, "interest"),
        }
        period_start: Optional[date] = None
        base_currency: Optional[str] = None
        ending_balances: dict[str, Decimal] = defaultdict(Decimal)
        forex_tickers: set[str] = set()
        cash_endings: dict[str, Decimal] = {}
        base_currency_summary_ending: Optional[Decimal] = None
        if True:
            reader = csv.reader(buffer)
            for row in reader:
                if not row:
                    continue
                row_len = len(row)
                section = row[0]
                row_kind = row[1].strip() if row_len > 1 else ""

                if section == "Statement" and row_kind == "Data" and row_len > 3:
                    field = row[2]
                    value = row[3].strip()
                    if field == "WhenGenerated" and value and (parts := value.split()):
                        abbreviation = parts[-1].upper()
                        zone_name = statement_timezones.get(abbreviation)
                        if zone_name is None:
                            raise ValueError(f"Unsupported statement timezone abbreviation '{abbreviation}'")
                        source_timezone = ZoneInfo(zone_name)
                    elif field == "Period":
                        period_parts = value.split("-", 1)
                        start_part = period_parts[0].strip()
                        period_start = datetime.strptime(start_part, "%B %d, %Y").date()
                    continue

                if section == "Account Information" and row_kind == "Data" and row_len > 3:
                    if row[2] == "Base Currency":
                        currency = row[3].strip().upper()
                        base_currency = currency or None
                    continue

                if section == "Open Positions":
                    if row_kind == "Data" and row_len >= 7 and row[2].strip() == "Summary":
                        ticker = row[5].strip()
                        quantity = parse_decimal(row[6])
                        if ticker and quantity is not None:
                            ending_balances[ticker] += quantity
                    continue

                if section == "Forex Balances":
                    if row_kind == "Data" and row_len >= 6:
                        ticker = row[4].strip().upper()
                        if ticker and not is_total_label(ticker):
                            quantity = parse_decimal(row[5])
                            if quantity is not None:
                                ending_balances[ticker] += quantity
                                forex_tickers.add(ticker)
                    continue

                if section == "Trades":
                    if row_kind == "Header":
                        commission_currency = None
                        if row_len > 11 and (label := row[11].strip()) and label.casefold() != "comm/fee":
                            if match := re.match(r"^Comm\s+in\s+([A-Z]{3})$", label, re.IGNORECASE):
                                commission_currency = match.group(1).upper()
                        continue

                    if row_kind != "Data" or row_len < 12 or row[2].strip() != "Order":
                        continue

                    asset_category = row[3].strip()
                    asset_category_cf = asset_category.casefold()
                    currency = row[4].strip().upper()
                    symbol = row[5].strip()
                    time = normalize_time(row[6], source_timezone)
                    quantity = parse_decimal(row[7])
                    raw_trade_price = parse_decimal(row[8])
                    trade_price = one if raw_trade_price is None else raw_trade_price
                    if "option" in asset_category_cf:
                        trade_price *= Decimal("100")
                    proceeds = parse_decimal(row[10])
                    fee = parse_decimal(row[11]) or zero

                    if quantity is None or proceeds is None:
                        continue

                    if asset_category_cf == "forex" and "." in symbol:
                        base, quote = symbol.split(".", 1)
                        base = base.strip().upper()
                        quote = quote.strip().upper()
                        if commission_currency == base:
                            asset_ticker, asset_qty, currency_ticker, currency_qty = quote, proceeds, base, quantity
                        else:
                            asset_ticker, asset_qty, currency_ticker, currency_qty = base, quantity, quote, proceeds
                        if base == "EUR":
                            trade_price = 1 / trade_price
                    else:
                        asset_ticker, asset_qty, currency_ticker, currency_qty = symbol, quantity, currency, proceeds

                    if commission_currency in (None, currency_ticker):
                        currency_qty += fee
                    elif commission_currency == asset_ticker:
                        asset_qty += fee

                    abs_currency_qty = abs(currency_qty)
                    if currency_ticker == "USD":
                        currency_price = self.currency_rate('USD', time.date())
                    elif currency_ticker == "EUR":
                        currency_price = one
                    else:
                        raise ValueError(f"Unsupported payment currency conversion from {currency_ticker} to EUR")

                    fee_note = "" if fee == zero else f" (fee {fmt_decimal(fee)} {commission_currency or currency_ticker})"
                    currency_description = f"{asset_category} currency leg ({symbol}){fee_note}"
                    asset_row = LedgerRow(asset_ticker, time, asset_qty, trade_price, abs_currency_qty, "trade", f"{asset_category} asset leg ({symbol})")
                    currency_row = LedgerRow(currency_ticker, time, currency_qty, currency_price, abs_currency_qty * currency_price, "trade", currency_description)
                    asset_row.force_set('cotx_id', currency_row.id)
                    currency_row.force_set('cotx_id', asset_row.id)
                    rows.extend((asset_row, currency_row))
                    continue

                if section == "Cash Report":
                    if row_kind != "Data" or row_len < 5:
                        continue

                    entry_name = row[2].strip()
                    currency = row[3].strip().upper()

                    if entry_name == "Ending Cash":
                        quantity = parse_decimal(row[4])
                        if quantity is None:
                            continue
                        if currency == "BASE CURRENCY SUMMARY":
                            base_currency_summary_ending = quantity
                        elif currency and not is_total_label(currency):
                            cash_endings[currency] = quantity
                        continue

                    if entry_name == "Starting Cash":
                        cash_report_scope = currency
                        continue

                    if (
                        entry_name != "Sales Tax"
                        or not currency
                        or currency == "BASE CURRENCY SUMMARY"
                        or cash_report_scope != currency
                    ):
                        continue

                    quantity = parse_decimal(row[4])
                    if quantity is None or quantity == zero:
                        continue

                    sales_taxes.append((currency, quantity))
                    continue

                if row_kind != "Data":
                    continue

                if (section_cols := section_columns.get(section)) is not None:
                    if section == "Fees" and row_len > 2 and is_total_label(row[2]):
                        continue

                    currency_idx, time_idx, description_idx, amount_idx, row_type = section_cols
                    if row_len <= amount_idx:
                        continue
                    ticker = row[currency_idx].strip().upper()
                    quantity = parse_decimal(row[amount_idx])
                    if (
                        not ticker
                        or is_total_label(ticker)
                        or quantity is None
                        or quantity == zero
                        or row_len <= time_idx
                        or not row[time_idx].strip()
                    ):
                        continue
                    time = normalize_time(row[time_idx], source_timezone)
                    description = f"{section}: {row[description_idx].strip() if row_len > description_idx else ''}"
                    if section == "Fees":
                        fee_dates.append(time)
                        if row_len > 2 and row[2].strip():
                            description = f"{section} ({row[2].strip()}): {row[5].strip()}"
                    payment_currency = abs(quantity) if section == "Deposits & Withdrawals" else zero
                    price = self.currency_rate('USD', time.date()) if ticker == "USD" else one
                    rows.append(LedgerRow(ticker, time, quantity, price, payment_currency, row_type, description))
                    continue

                if section == "Transfers":
                    if row_len < 15 or is_total_label(row[2]):
                        continue
                    asset_category = row[2].strip()
                    currency = row[3].strip().upper()
                    symbol = row[4].strip()
                    time = normalize_time(row[5], source_timezone)
                    transfer_type = row[6].strip()
                    direction = row[7].strip()

                    quantity = parse_decimal(row[10])
                    if quantity is not None and quantity != zero and symbol:
                        transfer_price = 0 # TODO: import this somehow?
                        rows.append(LedgerRow(symbol, time, quantity, transfer_price, zero, "transfer", f"Transfers {asset_category} {transfer_type} {direction}".strip()))

                    cash_amount = parse_decimal(row[14])
                    if cash_amount is not None and cash_amount != zero and currency:
                        cash_price = self.currency_rate('USD', time.date()) if currency == "USD" else one
                        rows.append(LedgerRow(currency, time, cash_amount, cash_price, zero, "transfer", f"Transfers cash {transfer_type} {direction} ({symbol})".strip()))
                    continue

        if period_start is None:
            raise ValueError(f"Statement period row not found")

        for ticker, quantity in cash_endings.items():
            ending_balances.setdefault(ticker, quantity)

        if (
            base_currency
            and base_currency_summary_ending is not None
            and base_currency not in ending_balances
            and base_currency not in cash_endings
        ):
            ending_balances[base_currency] = base_currency_summary_ending

        if sales_taxes and not fee_dates:
            raise ValueError("Unable to determine sales tax time")

        if sales_taxes:
            sales_tax_time = max(fee_dates)
            for ticker, quantity in sales_taxes:
                tax_price = self.currency_rate('USD', sales_tax_time.date()) if ticker == "USD" else one
                rows.append(LedgerRow(ticker, sales_tax_time, quantity, tax_price, zero, "tax", "Cash Report: Sales Tax"))


        if self.starting_balances:
            current_balances: dict[str, Decimal] = defaultdict(Decimal, self.starting_balances)
            for row in rows:
                current_balances[row.ticker] += row.quantity

            errors = []
            for ticker in sorted(ending_balances):
                diff = ending_balances[ticker] - current_balances.get(ticker, zero)
                if diff == zero:
                    continue
                if ticker in forex_tickers and abs(diff) <= Decimal("0.001"):
                    adj_time = normalize_time(period_start.isoformat(), source_timezone)
                    adj_price = self.currency_rate('USD', adj_time.date()) if ticker == "USD" else one
                    rows.append(LedgerRow(
                        ticker, adj_time, diff, adj_price, zero, "adjustment",
                        "Forex balance precision alignment to statement quantity",
                    ))
                    continue

                max_time = max(r.time for r in rows)
                min_time = min(r.time for r in rows)
                errors.append(
                    f"Unexplained balance difference for {ticker}: {fmt_decimal(diff)}. File: {ending_balances[ticker]}. System: {current_balances.get(ticker, zero)}. Max time: {max_time}. Min time: {min_time}."
                )

            if errors:
                raise ValueError('\n'.join(errors))


        return [r.export() for r in rows]


